config/routes.rb
Rails.application.routes.draw do
  resources :budgets do
    resources :budget_items
  end
  resources :projections
  resources :expenditures
  resources :payments
  resources :vendors
  resources :categories
  resources :expenses
  resources :charts
  # resources :budget_items
  root to: 'expenses#index'
  devise_for :users
  resources :users

  get "/fetch_months"   => 'expenses#selected_month', as: 'fetch_months'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :budget_items
end

app/models/budget_item.rb
class BudgetItem < ApplicationRecord
  belongs_to :budget

  def category
    Category.find(self.category_id).description
  end
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :user
	validates :description, presence: true, uniqueness: :true

	
end

app/models/charts.rb
class Charts
  
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord

  def total
    total = 0
    self.each { |n| total += n.amount }
    total
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
validates :date, presence: :true
validates :category_id, presence: :true
validates :amount, presence: :true
has_one :category
has_one :payment


	def category
		Category.find(self.category_id).description
	end

	def vendor
		Vendor.find(self.vendor_id).name
	end

	def payment
		Payment.find(self.payment_id)
	end

	def self.search(search)
 		where('extract(month from date) = ?', "#{search}")
	end

  def self.year(year)
    where('extract(year from date) = ?', "#{year}")
  end

  def self.month(month)
    where('extract(month from date) = ?', "#{month}")
  end

  # def expense_by_month
  #   # expenses_by_month = expenses.group_by { |expense|  expense.date.month }
  #   summed = [['Jan', 0.00],['Feb', 0.00],['Mar', 0.00],['Apr', 0.00],['May', 0.00],['Jun', 0.00],
  #              ['Jul', 0.00],['Aug', 0.00],['Sep', 0.00],['Oct', 0.00],['Nov', 0.00],['Dec', 0.00]]  
  #   self.each do |e|
  #     summed[e.date.month - 1][1] += e.amount
  #   end
  #   summed
  # end
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
	belongs_to :expense 
	belongs_to :category 
end

app/models/payment.rb
class Payment < ApplicationRecord
	has_attached_file :logo, :styles => { :thumb => "60x60>", :tiny => "15x15" }, :default_url => "/images/silouhette.png", dependent: :destroy
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/models/projection.rb
class Projection < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories
  has_many :expenses
  has_many :projections, dependent: :destroy
  has_many :budgets, dependent: :destroy
end

app/models/vendor.rb
class Vendor < ApplicationRecord

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @user = current_user
    @budgets = @user.budgets.order(:date)
    @budgets = Budget.all
    @budget = Budget.new
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    @budget_item = BudgetItem.new
    @categories = current_user.categories.order('description ASC')
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :index }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:date, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mobile_device
    agent = request.user_agent
    return "tablet" if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    return "mobile" if agent =~ /Mobile/
    return "desktop"
  end
  def total(array)
    total = 0
    array.each { |n| total += n.amount }
    total
  end
  def total_cash(array)
    total = 0
    array.each do |n| 
      if n.cash?
        total += n.amount
      end
    end
    total
  end
end

app/helpers/budget_items_helper.rb
module BudgetItemsHelper
  def total_budget(budget_items)
   budget_items.pluck(:amount).sum
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
  # def total_expenses(expenses)  This helper method is also in expenses and is redundant. 
  #   expenses.pluck(:amount).sum
  # end

  def monthly_average(expenses)
    divisor = expenses.group_by { |e| e.date.beginning_of_month }.count if expenses
    total_expenses(expenses)/divisor
  end

  def group_by_categories(expenses)
    expenses.group_by { |e| e.category_id }
  end

  def category_name(expenses)
    Category.find(group_by_categories(expenses).first.first).description
  end

  def category_sum(expenses)

  end

  def display_category_details(expenses)
  end

  def sum_category(expenses, category)
    total = 0
    expenses.each do |e| 
      if e.category_id == category.id 
        total += e.amount 
      end
    end
    total
  end

  def display_average_expenses_by_category(expenses)
    Category.all.each do |c|
      c.description  
      sum_category(expenses, c)
    end
  end


end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper

	def category_array(expense)
		array = []
		Category.all { |c| array << c.description}
		array.join(",")
	end

	def total_expenses(expenses)
		expenses.pluck(:amount).sum
	end

	def find_expenses_by_month(year, month, user)
		expenses = current_user.expenses.where('extract(year  from date) = ?', year)
		expenses.where('extract(month from date) = ?', month)
	end

	def make_pie(expenses)
		expenses.map {|k, v| [get_category(k).description, v] }
	end

	def get_category(id)
		Category.find(id)
	end
  
  
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/projections_helper.rb
module ProjectionsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/budgets/_budget_item_form.html.erb
<div id="budget-item-form" class="row">
  <div id="hide-budget-item-button" class="button tiny radius secondary">
    CANCEL
  </div>
  <%= form_for [@budget, @budget_item] do |f| %>

    <div class="row form-field">

      <div id="category-buttons" class="small-12 columns">
        <%= f.label :category_id, "Category" %>
        <%= f.hidden_field :category_id, id: "category-field", value: @budget_item.category_id %>
      <div>

      <div class="validation-box">
        <div class="orange-square">
          <%= fa_icon('exclamation') %>
          </div>
            Please choose a category. <div class="arrow_box"></div>
      </div> 
      <div id="add-category-button">
        <%= link_to "+", budgets_path %>
        </div>
          
        <div>
        <!-- Begin display categories -->
        <% @categories.each do |category| %>
          <div class="category-button">
            <%= link_to category.description, 'javascript:;' %>
            <span class="hidden-id"><%= category.id %></span>
          </div>
          <% end %>
        <!-- End display categories -->
        <div>
          <br><br>
    </div>
    <div class="form-field">
      
      <%= f.label :amount, "Amount"  %>
      <%= f.text_field :amount, class: "radius", required: true %>
      <%= f.label :description  %>
      <%= f.text_field :description, class: "radius" %>
      <%= f.hidden_field :budget_id, value: @budget.id %>
    </div>
  </div>


    <div class="actions">
      <%= f.submit 'ADD', class: 'button small rounded wide-button success' %>
    </div>
  <% end %>
</div>
</div></div></div>

app/views/budgets/_charts.html.erb
<% if current_user %>
  <div  class="">
    <div class="month-chart">
      <%= pie_chart make_pie(@budget.budget_items.group(:category_id).sum(:amount)),
                                prefix: "$",decimal: ".", donut: true %>
    </div>

    <div class="chart small-12 columns">
      <br>
      <%= column_chart make_pie(@budget.budget_items.group(:category_id).sum(:amount)),
                                prefix: "$",decimal: "." %>
    </div>

    <div class="chart small-12 columns">
      <br>
      <%= column_chart [
  { name: 'Budget', data: @budget.budget_items.group(:category_id).sum(:amount) },
  { name: 'Expenses', data: @budget.budget_items.group(:category_id).sum(:amount) }
], library: { scales: { yAxes: [{ ticks: { beginAtZero: true } }] } } %>

    
  </div>
<% end  %>

app/views/budgets/_form.html.erb
<div class="row">
  <div id="hide-show-button" class="button tiny radius secondary">
    CANCEL
  </div>
  
  <%= form_for(@budget) do |f| %>

    <div class="field">
      <%= f.label :date %>
      <% if mobile_device == "mobile" %>
        <%= f.date_field :date, id: "mobile-date", class: "radius", required: true %>
      <% else %>
        <%= f.text_field :date, id: "date", class: "radius", required: true %>
      <% end %>
    </div>


    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="actions">
      <%= f.submit 'ADD', class: 'button small radius wide-button success' %>
    </div>
  <% end %>
</div>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <div id="budget-form">
      <%= render 'form' %>
    </div>
    <div class="row">
      <h4><strong>Current Budgets</strong></h4>
      <% @budgets.each do |e| %>
        <div class=" row">
          <%= link_to budget_path(e) do %>
          <div class=""><h5><%= e.date.try(:strftime, "%b %-d, %Y") %> Budget</h5></div>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
    <div class="row">
      <div id="new-budget-button" class="button small rounded radius">ADD BUDGET</div>
    </div>
</div>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<div class="row">
  <div class="small-12 columns">

    <div class="row">
      <h4>
        <strong><%= @budget.date.try(:strftime, "%b, %Y") %> Budget</strong>
      </h4>
    </div>

    <div id="">
      <%= render 'budget_item_form' %>
    </div>

    
    <div>
    <table class=" small-12 columns">
      <thead>
        <tr>
          <th width="200" class="small-text show-for-medium-up"></th>
          <th width="200" class="small-text"></th>
          <th width="100" class="small-text"></th>

        </tr>
      </thead>

          <tbody id="expense-table">
      
          <% @budget.budget_items.each do |bi| %>
            <tr>
          
              <td><%= bi.category %></td>
              <td><%= bi.description %></td>
              <td><%= number_to_currency(bi.amount) %> <%= link_to fa_icon("times"), [@budget, bi], method: :delete, data: { confirm: 'Are you sure?' }, class: "right delete-expense" %></td>
            </tr>
          <% end %>
          <tr>
              <td><strong>Total:</strong></td>
              <td></td>
              <td><strong><%= number_to_currency(total_budget(@budget.budget_items)) %></strong></td>
            </tr>
      </tbody>
    </table>
    </div>

    <div class="row">
      <div id="new-budget-item-button" class="button small rounded radius">ADD BUDGET ITEM</div>
    </div>

    <%= render 'charts' %>

    <%= link_to 'Back', budgets_path %>
  </div>
</div>