config/routes.rb
Rails.application.routes.draw do
  resources :budgets do
    resources :budget_items
  end
  resources :projections
  resources :expenditures
  resources :payments
  resources :vendors
  resources :categories
  resources :expenses
  resources :charts
  # resources :budget_items
  root to: 'expenses#index'
  devise_for :users
  resources :users

  get "/fetch_months"   => 'expenses#selected_month', as: 'fetch_months'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :budget_items
end

app/models/budget_item.rb
class BudgetItem < ApplicationRecord
  belongs_to :budget

  def category
    Category.find(self.category_id).description
  end
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :user
	validates :description, presence: true, uniqueness: :true

	
end

app/models/charts.rb
class Charts
  
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord

  def total
    total = 0
    self.each { |n| total += n.amount }
    total
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
validates :date, presence: :true
validates :category_id, presence: :true
validates :amount, presence: :true
has_one :category
has_one :payment


	def category
		Category.find(self.category_id).description
	end

	def vendor
		Vendor.find(self.vendor_id).name
	end

	def payment
		Payment.find(self.payment_id)
	end

	def self.search(search)
 		where('extract(month from date) = ?', "#{search}")
	end

  def self.year(year)
    where('extract(year from date) = ?', "#{year}")
  end

  def self.month(month)
    where('extract(month from date) = ?', "#{month}")
  end

  # def expense_by_month
  #   # expenses_by_month = expenses.group_by { |expense|  expense.date.month }
  #   summed = [['Jan', 0.00],['Feb', 0.00],['Mar', 0.00],['Apr', 0.00],['May', 0.00],['Jun', 0.00],
  #              ['Jul', 0.00],['Aug', 0.00],['Sep', 0.00],['Oct', 0.00],['Nov', 0.00],['Dec', 0.00]]  
  #   self.each do |e|
  #     summed[e.date.month - 1][1] += e.amount
  #   end
  #   summed
  # end
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
	belongs_to :expense 
	belongs_to :category 
end

app/models/payment.rb
class Payment < ApplicationRecord
	has_attached_file :logo, :styles => { :thumb => "60x60>", :tiny => "15x15" }, :default_url => "/images/silouhette.png", dependent: :destroy
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/models/projection.rb
class Projection < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories
  has_many :expenses
  has_many :projections, dependent: :destroy
  has_many :budgets, dependent: :destroy
end

app/models/vendor.rb
class Vendor < ApplicationRecord

end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :set_expenditure, only: [:show, :edit, :update, :destroy]

  # GET /expenditures
  # GET /expenditures.json
  def index
    @expenditure = Expenditure.new
    @expenditures = Expenditure.all.order('due_date ASC')
  end

  # GET /expenditures/1
  # GET /expenditures/1.json
  def show
  end

  # GET /expenditures/new
  def new
    @expenditure = Expenditure.new
  end

  # GET /expenditures/1/edit
  def edit
  end

  # POST /expenditures
  # POST /expenditures.json
  def create
    @expenditure = Expenditure.new(expenditure_params)

    respond_to do |format|
      if @expenditure.save
        format.html { redirect_to :back }
        format.json { render :show, status: :created, location: @expenditure }
      else
        format.html { render :back,
          alert: "Oops, try that again. Enter due date, amount, and description." 
          }
        format.json { 
          render json: @expenditure.errors, 
          status: :unprocessable_entity 
          }
      end
    end
  end

  # PATCH/PUT /expenditures/1
  # PATCH/PUT /expenditures/1.json
  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        format.html { redirect_to expenditures_path }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1
  # DELETE /expenditures/1.json
  def destroy
    @expenditure.destroy
    respond_to do |format|
      format.html { redirect_to expenditures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expenditure
      @expenditure = Expenditure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expenditure_params
      params.require(:expenditure).permit(:amount, :due_date, :comment, :user_id, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mobile_device
    agent = request.user_agent
    return "tablet" if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    return "mobile" if agent =~ /Mobile/
    return "desktop"
  end
  def total(array)
    total = 0
    array.each { |n| total += n.amount }
    total
  end
  def total_cash(array)
    total = 0
    array.each do |n| 
      if n.cash?
        total += n.amount
      end
    end
    total
  end
end

app/helpers/budget_items_helper.rb
module BudgetItemsHelper
  def total_budget(budget_items)
   budget_items.pluck(:amount).sum
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
  # def total_expenses(expenses)  This helper method is also in expenses and is redundant. 
  #   expenses.pluck(:amount).sum
  # end

  def monthly_average(expenses)
    divisor = expenses.group_by { |e| e.date.beginning_of_month }.count if expenses
    total_expenses(expenses)/divisor
  end

  def group_by_categories(expenses)
    expenses.group_by { |e| e.category_id }
  end

  def category_name(expenses)
    Category.find(group_by_categories(expenses).first.first).description
  end

  def category_sum(expenses)

  end

  def display_category_details(expenses)
  end

  def sum_category(expenses, category)
    total = 0
    expenses.each do |e| 
      if e.category_id == category.id 
        total += e.amount 
      end
    end
    total
  end

  def display_average_expenses_by_category(expenses)
    Category.all.each do |c|
      c.description  
      sum_category(expenses, c)
    end
  end


end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper

	def category_array(expense)
		array = []
		Category.all { |c| array << c.description}
		array.join(",")
	end

	def total_expenses(expenses)
		expenses.pluck(:amount).sum
	end

	def find_expenses_by_month(year, month, user)
		expenses = current_user.expenses.where('extract(year  from date) = ?', year)
		expenses.where('extract(month from date) = ?', month)
	end

	def make_pie(expenses)
		expenses.map {|k, v| [get_category(k).description, v] }
	end

	def get_category(id)
		Category.find(id)
	end
  
  
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/projections_helper.rb
module ProjectionsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/expenditures/_form.html.erb
<div class="row">
<div id="hide-expenditure-button" class="button tiny radius secondary">CANCEL</div>
  
  <%= form_for @expenditure do |f| %>
    <% if @expenditure.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@expenditure.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% @expenditure.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, class: "radius", required: true %>
    </div>

    <div class="field">
      <%= f.label :amount %>
      <%= f.text_field :amount, class: "radius", required: true %>
    </div>

    <div class="field">
      <%= f.label :due_date %>
      <% if mobile_device == "mobile" %>
        <%= f.date_field :due_date, id: "mobile-due-date", class: "radius", required: true %>
      <% else %>
        <%= f.text_field :due_date, id: "due-date", class: "radius", required: true %>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment, class: "radius" %>
    </div>

    <div class="actions">
      <%= f.submit 'ADD', class: 'button small radius wide-button success' %>
    </div>
  <% end %>
</div>

app/views/expenditures/edit.html.erb
<h1>Editing Expenditure</h1>

<%= render 'form', expenditure: @expenditure %>

<%= link_to 'Show', @expenditure %> |
<%= link_to 'Back', expenditures_path %>

app/views/expenditures/index.html.erb
<p id="notice"><%= notice %></p>
<div id="expenditures" class="row">
  <div class="small-12 columns">
    <div class="row">
      <div id="new-expenditure-button" class="button small rounded radius">ADD EXPENDITURE</div>
    </div>
    <div id="expenditure-form">
      <%= render 'form' %>
    </div>
    <% @expenditures.each do |e| %>
      <div class=" row wish-item">
        <%= link_to expenditure_path(e) do %>
            <div class="small-4 columns"><h5><%= e.description %></h5></div>
        <% end %>
        <div class="small-3 columns text-right"><h5><%= e.due_date.try(:strftime, '%B') %></h5></div>
        <div class="small-4 columns text-right"><h5><%= number_to_currency(e.amount) %></h5></div>
        <div class="small-1 columns text-right"><h5><%= link_to fa_icon("times"), e, method: :delete, data: { confirm: 'Are you sure?' }, class: "right delete-expense" %></h5></div>
      </div>
    <% end %>
    <div class="total ">Total: <span class="right"><%= number_to_currency(total(@expenditures)) %></span></div>
  </div>
</div>

app/views/expenditures/new.html.erb
<h1>New Expenditure</h1>

<%= render 'form', expenditure: @expenditure %>

<%= link_to 'Back', expenditures_path %>

app/views/expenditures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @expenditure.amount %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @expenditure.due_date %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @expenditure.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @expenditure.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expenditure.description %>
</p>

<%= link_to 'Edit', edit_expenditure_path(@expenditure) %> |
<%= link_to 'Back', expenditures_path %>