config/routes.rb
Rails.application.routes.draw do
  resources :budgets do
    resources :budget_items
  end
  resources :projections
  resources :expenditures
  resources :payments
  resources :vendors
  resources :categories
  resources :expenses
  resources :charts
  # resources :budget_items
  root to: 'expenses#index'
  devise_for :users
  resources :users

  get "/fetch_months"   => 'expenses#selected_month', as: 'fetch_months'
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:index]
  before_action :set_expenses, only: [:index, :charts]

  # GET /expenses
  # GET /expenses.json
  def index
    @expense = Expense.new
    if current_user
      @expenses = @current_user_expenses.where('date >= ? AND date <= ?',
                                         DateTime.now.beginning_of_month,
                                 DateTime.now.end_of_month).order("date DESC")
      @yearly_expenses = @current_user_expenses.where('date >= ? AND date <= ?',
                                                DateTime.now.beginning_of_year,
                                                DateTime.now).order("date DESC")
      if params[:year] 
        @expenses = @current_user_expenses.year(params[:year]).order("date DESC")
      end
      if params[:month] 
        @expenses = @expenses.month(params[:month]).order("date DESC")
      end
      unless params[:year] == "" || params[:year] == nil
        @yearly_expenses = @current_user_expenses.year(params[:year]).order("date DESC")
      end
      @dates =  @yearly_expenses.all.select("date").map{ |i| i.date.month }.uniq
      @years =  @current_user_expenses.all.select("date").map{ |i| i.date.year }.uniq
    end
    @payments = Payment.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/ediź
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params.merge({user_id: current_user.id}))

    respond_to do |format|
      if @expense.save
        format.html { redirect_to :back }
        format.json { redirect_to :back, status: :created, location: @expense }
      else
        format.html { redirect_to :back,
          alert: "Oops, try that again. Choose date, amount, and category."
          }
        format.json {
          render json: @expense.errors,
          status: :unprocessable_entity
          }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { render :index }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  def selected_month
    @selected = Expense.where('date >= ? AND date <= ?', DateTime.now.beginning_of_month, DateTime.now.end_of_month).order("date DESC")
    respond_to do |format|
        format.js
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:amount, :date, :category_id, :vendor_id, :user_id, :comment, :payment_id)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def set_categories
    if current_user
      @categories = current_user.categories.order('description ASC')
    else
      @categories = []
    end
    @category = Category.new
  end

  def set_expenses
    if current_user
      @current_user_expenses = current_user.expenses
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper

	def category_array(expense)
		array = []
		Category.all { |c| array << c.description}
		array.join(",")
	end

	def total_expenses(expenses)
		expenses.pluck(:amount).sum
	end

	def find_expenses_by_month(year, month, user)
		expenses = current_user.expenses.where('extract(year  from date) = ?', year)
		expenses.where('extract(month from date) = ?', month)
	end

	def make_pie(expenses)
		expenses.map {|k, v| [get_category(k).description, v] }
	end

	def get_category(id)
		Category.find(id)
	end
  
  
end

app/views/expenses/_category_form.html.erb
<!-- category-form -->
<div id="category-form">
  <%= form_for @category do |f| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        Oops, try again!
      </div>
    <% end %>
    <%= f.text_field :description, id: "category-input",:autofocus => true %>
    <%= f.submit "+", id: "add-cat", class: 'add-category-button' %>
  <% end %>
</div>
<!-- category-form -->

app/views/expenses/_charts.html.erb
<!-- Bad Code! Fix Soon! -->
<!-- May -->
<% if current_user %>
	<div  class="month-chart">
		<br>
		<div class="chart small-12 columns">
			<h6>DAILY SPENDING</h6>
			<%= line_chart find_expenses_by_month(params[:year], params[:month],
																				current_user).group(:date).sum(:amount),
			 																	prefix: "$",decimal: "." %>
		</div>
		<br>
		<div class="chart small-12 columns">
			<h6>AVERAGE BY CATEGORY</h6>
			<%= pie_chart make_pie(find_expenses_by_month(params[:year], params[:month],
																current_user).group(:category_id).sum(:amount)),
																prefix: "$",decimal: ".", donut: true %>
		</div>

		<div class="chart small-12 columns">
			<br>
			<%= column_chart make_pie(find_expenses_by_month(params[:year], params[:month],
																current_user).group(:category_id).sum(:amount)),
																prefix: "$",decimal: ".", donut: true %>
		</div>
	</div>
<% end  %>

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
 

  <div class="small-12 columns">
    <%= f.label :date %>
    <% if mobile_device == "mobile" %>
      <%= f.date_field :date, id: "mobile-date", class: "radius", required: true %>
    <% else %>
      <%= f.text_field :date, id: "date", class: "radius", required: true %>
    <% end %>
  </div>
  <div id="amount" class="small-12 columns">
    <%= f.label :amount %>
    <%= f.text_field :amount, class: "radius", required: true %>
  </div>
  <div id="category-buttons" class="small-12 columns">
    <%= f.label :category_id, "Category" %>
    <%= f.hidden_field :category_id, id: "category-field", value: @expense.category_id %>
    <div>
    <div class="validation-box">

      <div class="orange-square"><%= fa_icon('exclamation') %></div>
        Please choose a category.<div class="arrow_box"></div></div> 
      <div id="add-category-button"><%= link_to "+", expenses_path %></div>
      <!-- Begin display categories -->
      <% @categories.each do |category| %>
        <div class="category-button">
          <%= link_to category.description, 'javascript:;' %>
          <span class="hidden-id"><%= category.id %></span>
        </div>
        <% end %>
      <!-- End display categories -->
    </div>
  </div>


  <div>
    <%= link_to fa_icon("comment"), 'javascript:;', id: "comment-icon" %>
  </div>
  
  <div id="add-comment" class="hideable">
    <%= f.label "Comment" %>
    <%= f.text_area :comment, class: "radius", autofocus: true %>
  </div>

  <!-- This is available to display payment type. I find it unnecessary -->
  <!-- <div class="hideable">
    <ul id="payment-type">
      <%# @payments.each do |p| %>
      <li id=<%#= p.id %> class="payment-logo"><%#= image_tag p.logo.url(:thumb) %></li>
      <%# end %>
      <%#= f.hidden_field :payment_id, value: @expense.payment_id, id: "payment-id" %>
    </ul>
  </div> -->

  <div class="">
    <%= f.submit "ADD", id: "submit-expense", class: 'button small rounded wide-button success' %>
  </div>
<% end %>

<%= render 'category_form' %>
<%= render 'vendor_form' %>

app/views/expenses/_monthly_expenses.html.erb
<h5 id="month-header">

      <strong></strong>
    </h5>
    <table class="tight-table small-12 columns">
      <thead>
        <tr>
          <th width="100" class="small-text"></th>
          <th width="200" class="small-text show-for-medium-up"></th>
          <th width="200" class="small-text"></th>
          <th width="25" class="small-text"></th>
          <th width="75" class="small-text"></th>

        </tr>
      </thead>

          <tbody id="expense-table" data-internalid=<%= Date.today.month %>>
          <% @expenses.each do |expense| %>
            <tr>
              <td><%= expense.date.try(:strftime, '%-m/%d/%y') %></td>
              <td><%= expense.category %></td>
              <td class="show-for-medium-up"><%= expense.comment %></td>
              <td class="">
                <% if expense.payment_id? %>
                  <%= image_tag expense.payment.logo.url(:tiny) %></td>
                <% end %>
              <td><%= number_to_currency(expense.amount) %> <%= link_to fa_icon("times"), expense, method: :delete, data: { confirm: 'Are you sure?' }, class: "right delete-expense" %></td>
            </tr>
          <% end %>
          <tr>
              <td><strong>Total:</strong></td>
              <td></td>
              <td></td>
              <td class="show-for-medium-up"></td>
              <td><strong><%= number_to_currency(total_expenses(@expenses)) %></strong></td>
            </tr>
      </tbody>
    </table>
    <div class="row">
      <ul>
        <% @years.sort.each do |d| %>
        <li class="years" value =<%= d %>><%=link_to d, "#", data: d, remote: true %></li>
        <% end %>
      </ul>
    </div>
    <div class="row">
      <ul>
      <% @dates.sort.each do |d| %>
        <li class="months" value =<%= d %>><%=link_to Date::MONTHNAMES[d], "#", data: d, remote: true %></li>
      <% end %>
      </ul>
    </div>

app/views/expenses/_year_to_date.html.erb
<!-- Bad Code! Fix Soon! -->
<!-- May -->
<div  class="month-chart">
	<br>
	<div class="chart small-12 columns">
		<h6>Year To Date</h6>
		<div><strong>Total: <%= number_to_currency(total_expenses(@yearly_expenses)) %></strong></div>
		<%#= line_chart find_expenses_by_year(params[:search]).group(:date).sum(:amount),
		prefix: "$",decimal: "." %>
	</div>
	<!-- <br>
	<div class="chart small-12 columns">
		<h6>AVERAGE BY CATEGORY</h6>
		<%#= pie_chart make_pie(@yearly_expenses).group(:category_id).sum(:amount)),
		prefix: "$",decimal: ".", donut: true %>
	</div>

	<div class="chart small-12 columns">
		<br>
		<%#= column_chart make_pie(@yearly_expenses).group(:category_id).sum(:amount)),
		prefix: "$",decimal: ".", donut: true %>
	</div>
</div> -->

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<%= content_for :title, "Expenses" %>
<script type="text/javascript">
  var d = new Date();
  var n = d.getFullYear();
  var set_year = localStorage.getItem('year');
  if (set_year == "" || set_year === null ) {
    localStorage.setItem('year', n)
  }
  if (localStorage.getItem('month') == "") {
    localStorage.setItem('month', 0)
  }
</script>
<% unless signed_in? %>

  <div  class="row">
    <div class="small-12 medium-8 large-8 columns small-centered">
    <header id="title">
      <h1>Firelog</h1>
        <h4>Track My Burn Rate</h4>
    </header>
    <div class="row">
      <div id="home-message" class="small-12 medium-8 large-8 columns small-centered medium-centered large-centered ">
        <%= link_to "Get Started", new_user_registration_path, class: "button success radius" %>
      </div>
    </div>

    </div>
  </div>
<% else %>

<div class="row">
  <div>
  <%= render 'form' %>

  <div id="expenses-list" class="">
    <%= form_tag(expenses_path, :method => "get", id: "search-form") do %>
      <%#= hidden_field_tag :search, params[:search], id: "search-field" %>
      <%= hidden_field_tag :year, params[:year], id: "year-field" %>
      <%= hidden_field_tag :month, params[:month], id: "month-field" %>
    <% end %>
    <%= render 'monthly_expenses', locals: { expenses: @expenses} %>
  </div>

  </div>
</div>
<div class="row">
  <div class="small-12 columns small-centered">
  <%= render 'charts' %>
  </div>
</div>
<div class="row">
  <div class="small-12 columns small-centered">
  <%= render 'year_to_date' %>
  </div>
</div>
<% end %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expense.category_id %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @expense.vendor_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @expense.comment %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>